var timeAct=360; timeIni=360; timeBon=0;
var successes=0; successesMax=5; attempts=0; attemptsMax=99;
var score=0; scoreMax=5; scoreInc=1; scoreDec=1
var typeGame=0;
var tiTime=false;
var tiTimeType=1;
var tiButtonTime=false;
var textButtonTime="Comenzar";
var tiSuccesses=true;
var tiAttempts=true;
var tiScore=true;
var startTime;
var colorBack="#FFFDFD"; colorButton="#91962F"; colorText="#000000"; colorSele="#FF8000";
var goURLNext=false; goURLRepeat=false;tiAval=false;
var scoOk=0; scoWrong=0; scoOkDo=0; scoWrongDo=0; scoMessage=""; scoPtos=10;
var fMenssage="Verdana, Geneva, sans-serif";
var fActi="Verdana, Geneva, sans-serif";
var fEnun="Verdana, Geneva, sans-serif";
var timeOnMessage=2; messageOk="¡Correcto!"; messageTime=""; messageError="¡Incorrecto! corrige el error y sigue."; messageErrorG="¡Incorrecto! corrige el error y sigue."; messageAttempts=""; isShowMessage=false;
var urlOk=""; urlTime=""; urlError=""; urlAttempts="";
var goURLOk="_blank"; goURLTime="_blank"; goURLAttempts="_blank"; goURLError="_blank"; 
borderOk="#008000"; borderTime="#FF0000";borderError="#FF0000"; borderAttempts="#FF0000";
var wordsGame="MjBPRi1FbGVjdHJpY2lkYWQtRXNvMy0wMS1j"; wordsStr = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
function giveZindex(typeElement){var valueZindex=0; capas=document.getElementsByTagName(typeElement);
for (i=0;i<capas.length;i++){if (parseInt($(capas[i]).css("z-index"),10)>valueZindex){valueZindex=parseInt($(capas[i]).css("z-index"),10);}}return valueZindex;}
var words=["cGlsYS05ViBpbnRlcnJ1cHRvciBib21iaWxsYQ==","YmF0ZXLDrWEgcHVsc2Fkb3IgdGltYnJl","ZnVlbnRlLWRlLWFsaW1lbnRhY2nDs24gY29ubXV0YWRvciBtb3Rvci1ib21iaWxsYQ==","cGlsYS01ViBwdWxzYWRvciBkaW9kby1sZWQtdmVyZGU=","ZGluYW1vIGludGVycnVwdG9yIGJvbWJpbGxh"];imaW=["","","","",""];queW=["1) generador 2) elemento de maniobra 3) receptor","1) generador 2) elemento de maniobra 3) receptor","1) generador 2) elemento de maniobra 3) receptor","1) generador 2) elemento de maniobra 3) receptor","1) generador 2) elemento de maniobra 3) receptor"];altW=["","","","",""];c=[28,23,48,32,27];
var infoW=["","","","",""];
var auW=["","","","",""];
var actMaxWidth="700"; actMaxHeight="300";indexG=0;profG=0;dirMedia="20OF-Electricidad-Eso3-01-c_resources/media/"; textBNext="pulsar aquí para siguiente";
var wordsG=[];imageW=[];questionW=[];audioW=[];cG=[];alterW=[];informaW=[];
